export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-background": "#e0e3e5",
        "tertiary-fixed-dim": "#c3c6d6",
        "surface-container": "#1d2022",
        "secondary-fixed": "#d8e3fb",
        "on-error-container": "#ffdad6",
        "on-tertiary-container": "#4b4e5b",
        "surface-tint": "#2fd9f4",
        "on-primary-fixed": "#001f25",
        "outline-variant": "#3c494c",
        "surface-container-low": "#191c1e",
        "surface-container-lowest": "#0b0f10",
        "tertiary": "#d9dcec",
        "inverse-on-surface": "#2d3133",
        "surface-bright": "#363a3b",
        "on-secondary-fixed": "#111c2d",
        "primary-fixed-dim": "#2fd9f4",
        "on-tertiary": "#2c303c",
        "on-secondary-fixed-variant": "#3c475a",
        "background": "#101415",
        "secondary": "#bcc7de",
        "error": "#ffb4ab",
        "on-surface": "#e0e3e5",
        "on-tertiary-fixed": "#171b27",
        "tertiary-container": "#bdc0d0",
        "primary-fixed": "#a2eeff",
        "surface": "#101415",
        "error-container": "#93000a",
        "surface-dim": "#101415",
        "surface-variant": "#323537",
        "on-tertiary-fixed-variant": "#434653",
        "on-primary": "#00363e",
        "secondary-fixed-dim": "#bcc7de",
        "tertiary-fixed": "#dfe2f2",
        "on-secondary": "#263143",
        "on-surface-variant": "#bbc9cd",
        "surface-container-high": "#272a2c",
        "primary-container": "#22d3ee",
        "on-primary-container": "#005763",
        "outline": "#859397",
        "on-error": "#690005",
        "secondary-container": "#3e495d",
        "inverse-surface": "#e0e3e5",
        "primary": "#8aebff",
        "inverse-primary": "#006877",
        "on-primary-fixed-variant": "#004e5a",
        "on-secondary-container": "#aeb9d0",
        "surface-container-highest": "#323537"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "unit": "4px",
        "gutter": "24px",
        "stack-sm": "8px",
        "margin-mobile": "20px",
        "margin-desktop": "64px",
        "section-gap": "80px",
        "container-max": "1440px",
        "stack-md": "16px",
        "stack-lg": "32px"
      },
      fontFamily: {
        "body-lg": ["PT Sans Narrow", "sans-serif"],
        "body-md": ["PT Sans Narrow", "sans-serif"],
        "headline-lg-mobile": ["PT Sans Narrow", "sans-serif"],
        "title-md": ["PT Sans Narrow", "sans-serif"],
        "display-lg": ["PT Sans Narrow", "sans-serif"],
        "headline-lg": ["PT Sans Narrow", "sans-serif"],
        "label-mono": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "1.2", "fontWeight": "600"}],
        "title-md": ["20px", {"lineHeight": "1.4", "fontWeight": "500"}],
        "display-lg": ["48px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600"}],
        "label-mono": ["12px", {"lineHeight": "1.5", "letterSpacing": "0.05em", "fontWeight": "500"}]
      }
    },
  },
  plugins: [],
}
