/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#dae2fd",
        "on-surface-variant": "#584237",
        "on-primary-fixed-variant": "#783200",
        "on-tertiary-fixed": "#1a1c1c",
        "on-error-container": "#93000a",
        "surface-variant": "#dae2fd",
        secondary: "#555f6d",
        surface: "#faf8ff",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#283044",
        primary: "#9d4300",
        "on-secondary-container": "#596372",
        "on-primary": "#ffffff",
        tertiary: "#5d5f5f",
        "on-primary-fixed": "#341100",
        "surface-container": "#eaedff",
        "tertiary-fixed-dim": "#c6c6c7",
        "secondary-fixed-dim": "#bdc7d8",
        "error-container": "#ffdad6",
        outline: "#8c7164",
        "on-surface": "#131b2e",
        background: "#faf8ff",
        "inverse-on-surface": "#eef0ff",
        "surface-tint": "#9d4300",
        "surface-bright": "#faf8ff",
        "on-background": "#131b2e",
        "surface-dim": "#d2d9f4",
        "primary-fixed": "#ffdbca",
        "surface-container-low": "#f2f3ff",
        "secondary-fixed": "#d9e3f4",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#ffb690",
        "on-error": "#ffffff",
        "tertiary-fixed": "#e2e2e2",
        "on-secondary": "#ffffff",
        "tertiary-container": "#9a9b9b",
        "on-secondary-fixed": "#121c28",
        "primary-container": "#f97316",
        "on-secondary-fixed-variant": "#3e4755",
        "outline-variant": "#e0c0b1",
        "inverse-primary": "#ffb690",
        "on-tertiary-container": "#313333",
        "surface-container-high": "#e2e7ff",
        error: "#ba1a1a",
        "secondary-container": "#d6e0f1",
        "on-primary-container": "#582200",
        "on-tertiary-fixed-variant": "#454747",
      },
      fontFamily: {
        headline: ["Space Grotesk", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
        display: ["Space Grotesk", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      boxShadow: {
        custom: "0 4px 15px rgba(0, 0, 0, 0.08)",
        "custom-lg": "0 10px 30px rgba(0, 0, 0, 0.12)",
      },
    },
  },
  plugins: [],
}
