/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#d1fae5",
        "on-surface-variant": "#1e293b",
        "on-primary-fixed-variant": "#1e3a8a",
        "on-tertiary-fixed": "#064e3b",
        "on-error-container": "#93000a",
        "surface-variant": "#f1f5f9",
        secondary: "#10b981", // Emerald Green
        surface: "#f8fafc",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#1e293b",
        primary: "#1e40af", // Deep Blue
        "on-secondary-container": "#064e3b",
        "on-primary": "#ffffff",
        tertiary: "#059669",
        "on-primary-fixed": "#172554",
        "surface-container": "#e2e8f0",
        "tertiary-fixed-dim": "#a7f3d0",
        "secondary-fixed-dim": "#6ee7b7",
        "error-container": "#ffdad6",
        outline: "#64748b",
        "on-surface": "#0f172a",
        background: "#f8fafc",
        "inverse-on-surface": "#f1f5f9",
        "surface-tint": "#1e40af",
        "surface-bright": "#ffffff",
        "on-background": "#0f172a",
        "surface-dim": "#cbd5e1",
        "primary-fixed": "#dbeafe",
        "surface-container-low": "#f1f5f9",
        "secondary-fixed": "#d1fae5",
        "surface-container-lowest": "#ffffff",
        "primary-fixed-dim": "#bfdbfe",
        "on-error": "#ffffff",
        "tertiary-fixed": "#ecfdf5",
        "on-secondary": "#ffffff",
        "tertiary-container": "#d1fae5",
        "on-secondary-fixed": "#064e3b",
        "primary-container": "#3b82f6",
        "on-secondary-fixed-variant": "#065f46",
        "outline-variant": "#cbd5e1",
        "inverse-primary": "#60a5fa",
        "on-tertiary-container": "#064e3b",
        "surface-container-high": "#e2e8f0",
        error: "#ba1a1a",
        "secondary-container": "#10b981",
        "on-primary-container": "#ffffff",
        "on-tertiary-fixed-variant": "#065f46",
      },
      fontFamily: {
        headline: ["PT Sans Narrow", "sans-serif"],
        body: ["PT Sans Narrow", "sans-serif"],
        label: ["PT Sans Narrow", "sans-serif"],
        display: ["PT Sans Narrow", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      boxShadow: {
        custom: "0 4px 15px rgba(0, 0, 0, 0.08)",
        "custom-lg": "0 10px 30px rgba(0, 0, 0, 0.12)",
      },
    },
  },
  plugins: [],
}
